# 결측치 대체 / 삭제

- 명목형 변수들은 결측치를 'NaN' 이라는 문자열으로 대체 

- 연속형 변수들은 주변 칼럼을 참조하여 최대한 추정, 해결 안된 결측치들은 평균 대체

- int나 float값을 가지지만 명목 변수인 칼럼들도 존재, 이러한 칼럼들 수정

- 이후 과정은 module을 사용하여 진행 (Preprocessing 모듈의 Preprocess 클래스 참조)

In [1]:
def syspath(path) :
    if path not in sys.path :
        sys.path.append(path)
    else : pass

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sys
import warnings

warnings.filterwarnings('ignore')

In [12]:
syspath('./dataset/mod')

from Preprocessing import Preprocess

In [3]:
# 중복만 없앤 원본 데이터 불러오기
df_origin = pd.read_pickle('./dataset/00_feature_with_label.pkl')
df_origin.head()

IMP_TYPE_OF_DECLARATION_1 IMP_TYPE_OF_DECLARATION_2 TRD_TIN_2  \
0                        ИМ                       NaN       NaN   
1                        ИМ                       NaN       NaN   
2                        ИМ                       NaN       NaN   
3                        ИМ                       NaN       NaN   
4                        ИМ                       NaN       NaN   

                                          TRD_NAME_2 TRD_COUNTRY_2  \
0                                   ООО ВИП-ТРАНС               RU   
1                                   ООО ВИП-ТРАНС               RU   
2                                   ООО ВИП-ТРАНС               RU   
3  " М/С АКИДЖ ДУТЕ МИЛЛС ЛТД",Ч/З БАНДАР АБАС П/...            BD   
4  " М/С АКИДЖ ДУТЕ МИЛЛС ЛТД",Ч/З БАНДАР АБАС П/...            BD   

                                   TRD_ADDR_2 CUS_SHIPMENT_SPEC_4  \
0  НИЖНЕВАРТОВСК КУЗОВАТКИНА ДОМ 5 СТРОЕНИЕ 3                 NaN   
1  НИЖНЕВАРТОВСК КУЗОВАТКИНА ДОМ 5 СТРОЕНИЕ 3                 NaN   
2  НИЖНЕВАРТОВСК КУЗОВАТКИНА ДОМ 5 СТРОЕНИЕ 3                 NaN   
3                                     АББАС                   NaN   
4                                     АББАС                   NaN   

   CUS_TOTAL_NUMBER_OF_ITEMS_5  CUS_TOTAL_NUMBER_OF_PACKAGES_6  \
0                            1                            64.0   
1                            1                            64.0   
2                            1                            64.0   
3                            1                          1213.0   
4                            1                          1213.0   

            CUS_REF_NO_7  ...  PAM_FINANCIAL_VALUE_47  \
0  762235/140217/0000189  ...                  553.76   
1  762235/140217/0000189  ...                17286.89   
2  762235/140217/0000189  ...                62232.82   
3  762241/140217/0100665  ...                  553.76   
4  762241/140217/0100665  ...                 8662.33   

  CAL_METHOD_OF_PAYMENT_47 IMP_DATE_OF_DECLARATION_54 REP_TIN_54  \
0                       БН                   20170214  510000091   
1                       УН                   20170214  510000091   
2                       БН                   20170214  510000091   
3                       БН                   20170214  510000091   
4                       УН                   20170214  510000091   

                   PERSON_NAME_54 PERSON_POSITION_54 GEND_REFERENCE_54  \
0     ВАХОБОВ ШАВКАТ ТУРСУНБОЕВИЧ  СПЕЦИАЛИСТ ПО Т/О          СГ01/007   
1     ВАХОБОВ ШАВКАТ ТУРСУНБОЕВИЧ  СПЕЦИАЛИСТ ПО Т/О          СГ01/007   
2     ВАХОБОВ ШАВКАТ ТУРСУНБОЕВИЧ  СПЕЦИАЛИСТ ПО Т/О          СГ01/007   
3  САЙФИЕВА МАВЗУНА ШАРИФДЖАНОВНА         СПЕЦИАЛИСТ        СГ/01/0077   
4  САЙФИЕВА МАВЗУНА ШАРИФДЖАНОВНА         СПЕЦИАЛИСТ        СГ/01/0077   

  GEND_ISSUE_DATE_54              ACCEPTANCE_DATE  LABEL  
0         20150624.0  14.02.17 11:55:18,551000000      0  
1         20150624.0  14.02.17 11:55:18,551000000      0  
2         20150624.0  14.02.17 11:55:18,551000000      0  
3         20150624.0  14.02.17 15:53:44,921000000      0  
4         20150624.0  14.02.17 15:53:44,921000000      0  

[5 rows x 74 columns]

In [4]:
# 전체 null값 개수와 그 중 LABEL 1인 것들의 개수를 출력하는 함수 생성
def get_result(column_name) :
    mask1 = df_origin['{}'.format(column_name)].isnull()
    tmp_df = df_origin[mask1]
    mask2 = tmp_df.LABEL == 1
    
    print('##### {} #####'.format(column_name))
    print('Number of null : {}'.format(len(tmp_df)))
    print('Label 1 null : {}'.format(len(tmp_df[mask2])))
    return tmp_df

In [5]:
# 연속형 변수들을 함수에 대입하여 전체 null값 개수와 그 중 LABEL이 1인 것들의 개수를 확인

columns =  ['CUS_TOTAL_NUMBER_OF_PACKAGES_6', 'VAL_FINANCIAL_VALUE_12',
            'TOT_FINANCIAL_VALUE_22', 'IMP_EXCHANGE_RATE_23',
            'IMP_INLAND_TRANSPORT_MODE_25', 'IMP_TRANSPORT_MODE_AT_BODR_26',
            'GDS_GROSS_MASS_35', 'IDG_NET_MASS_38', 'FIN_FINANCIAL_VALUE_42',
            'STC_FINANCIAL_VALUE_46']

for column in columns : 
    get_result(column)

# 결과를 살펴보면 label = 1인 null값은 한개도 없음
# 따라서 null값의 수가 많은 column들(500개 이상)만 대체 고려,

##### CUS_TOTAL_NUMBER_OF_PACKAGES_6 #####
Number of null : 151
Label 1 null : 0
##### VAL_FINANCIAL_VALUE_12 #####
Number of null : 56
Label 1 null : 0
##### TOT_FINANCIAL_VALUE_22 #####
Number of null : 87
Label 1 null : 0
##### IMP_EXCHANGE_RATE_23 #####
Number of null : 11704
Label 1 null : 0
##### IMP_INLAND_TRANSPORT_MODE_25 #####
Number of null : 847
Label 1 null : 0
##### IMP_TRANSPORT_MODE_AT_BODR_26 #####
Number of null : 1020
Label 1 null : 0
##### GDS_GROSS_MASS_35 #####
Number of null : 567
Label 1 null : 0
##### IDG_NET_MASS_38 #####
Number of null : 590
Label 1 null : 0
##### FIN_FINANCIAL_VALUE_42 #####
Number of null : 162
Label 1 null : 0
##### STC_FINANCIAL_VALUE_46 #####
Number of null : 17
Label 1 null : 0


## IMP_EXCHANGE_RATE_23
- TOT_CURRENCY_22 = TJS 인 sample은 null값을 1로 대체 (자국 화폐이므로)

In [7]:
mask = (df_origin.TOT_CURRENCY_22 == 'TJS') & (df_origin.IMP_EXCHANGE_RATE_23.isnull())
idx = df_origin[mask].index
for i in idx :
    df_origin.iloc[i, 32] = 1
df_origin[mask]['IMP_EXCHANGE_RATE_23'].unique()

array([1.])

## IMP_INLAND_TRANSPORT_MODE_25, IMP_TRANSPORT_MODE_AT_BODR_26

In [6]:
# 출력값에서 볼 수 있듯이 이 둘은 float값을 지니고 있지만 사실상 명목 변수
print(df_origin.IMP_INLAND_TRANSPORT_MODE_25.unique())
print(df_origin.IMP_TRANSPORT_MODE_AT_BODR_26.unique())

[20. 30. 40. 90. nan 50. 70. 80. 10. 18. 23.]
[20. 30. 40. 90. nan 50. 70. 23. 80. 10.]


In [8]:
# null값 0으로 대체 후 int로 변환
for column in ['IMP_INLAND_TRANSPORT_MODE_25', 'IMP_TRANSPORT_MODE_AT_BODR_26'] :
    df_origin['{}'.format(column)].fillna(0, inplace=True)
    df_origin['{}'.format(column)] = df_origin['{}'.format(column)].astype(int)
    print(df_origin['{}'.format(column)].unique())

[20 30 40 90  0 50 70 80 10 18 23]
[20 30 40 90  0 50 70 23 80 10]


## GDS_GROSS_MASS_35, IDG_NET_MASS_38

In [9]:
# 해당하는 칼럼들만 추출하여 DataFrame 생성
edf = df_origin[['COM_COMBINED_NOMENCLATURE_33','GDS_GROSS_MASS_35', 'IDG_NET_MASS_38']]
edf

COM_COMBINED_NOMENCLATURE_33  GDS_GROSS_MASS_35  IDG_NET_MASS_38
0                          4410110009           128000.0         121145.0
1                          4410110009           128000.0         121145.0
2                          4410110009           128000.0         121145.0
3                          5307200000            46640.0          45000.0
4                          5307200000            46640.0          45000.0
...                               ...                ...              ...
2148121                    8703239013             1610.0           1610.0
2148122                    8703239013             1610.0           1610.0
2148123                    4011990000              204.0            204.0
2148124                    4011990000              204.0            204.0
2148125                    9018908409              600.0            600.0

[2148126 rows x 3 columns]

In [10]:
# null값 대체를 위한 사용자 함수 생성

def translation(column_name) :

  # 해당 칼럼의 null값이 있는 샘플만 인덱싱하여 해당 샘플의 인덱스와 HS-CODE를 리스트로 저장 
  mask = edf[column_name].isnull()
  idx_list = edf[mask].index.tolist()
  hs_list = edf[mask]['COM_COMBINED_NOMENCLATURE_33'].unique().tolist()

  # HS-CODE별로 GDS_GROSS_MASS_35, IDG_NET_MASS_38의 평균 산출 후 dictionary 생성 
  mean_list = []
  for code in hs_list :
    mask = edf['COM_COMBINED_NOMENCLATURE_33'] == code
    mean = edf[mask][column_name].mean()
    mean_list.append(mean)
  mean_dict = dict(zip(hs_list, mean_list))

  # dictionary를 사용하여 null값 대체 
  for i in idx_list :
    val = edf.iloc[i, 0]
    if column_name == 'GDS_GROSS_MASS_35' :
      edf.iloc[i, 1] = mean_dict[val]
    elif column_name == 'IDG_NET_MASS_38' :
      edf.iloc[i, 2] = mean_dict[val]

for column in ['GDS_GROSS_MASS_35', 'IDG_NET_MASS_38'] :
  translation(column)

for column in ['GDS_GROSS_MASS_35', 'IDG_NET_MASS_38'] :
  df_origin[column] = edf[column]

In [11]:
# null값이 100개 대로 줄어든 것을 확인 가능
columns =  ['CUS_TOTAL_NUMBER_OF_PACKAGES_6', 'VAL_FINANCIAL_VALUE_12',
            'TOT_FINANCIAL_VALUE_22', 'IMP_EXCHANGE_RATE_23',
            'IMP_INLAND_TRANSPORT_MODE_25', 'IMP_TRANSPORT_MODE_AT_BODR_26',
            'GDS_GROSS_MASS_35', 'IDG_NET_MASS_38', 'FIN_FINANCIAL_VALUE_42',
            'STC_FINANCIAL_VALUE_46']

for column in columns : 
    get_result(column)

##### CUS_TOTAL_NUMBER_OF_PACKAGES_6 #####
Number of null : 151
Label 1 null : 0
##### VAL_FINANCIAL_VALUE_12 #####
Number of null : 56
Label 1 null : 0
##### TOT_FINANCIAL_VALUE_22 #####
Number of null : 87
Label 1 null : 0
##### IMP_EXCHANGE_RATE_23 #####
Number of null : 58
Label 1 null : 0
##### IMP_INLAND_TRANSPORT_MODE_25 #####
Number of null : 0
Label 1 null : 0
##### IMP_TRANSPORT_MODE_AT_BODR_26 #####
Number of null : 0
Label 1 null : 0
##### GDS_GROSS_MASS_35 #####
Number of null : 12
Label 1 null : 0
##### IDG_NET_MASS_38 #####
Number of null : 12
Label 1 null : 0
##### FIN_FINANCIAL_VALUE_42 #####
Number of null : 162
Label 1 null : 0
##### STC_FINANCIAL_VALUE_46 #####
Number of null : 17
Label 1 null : 0


In [13]:
# 나머지 null값은 이전과 같이 평균 대체 진행
pre_df_origin = Preprocess(df_origin)
basic_feature_df = pre_df_origin.null_solution()
basic_feature_df.isnull().sum()

# 결측값이 모두 제거된 것을 확인 가능

TRD_NAME_2                        0
TRD_COUNTRY_2                     0
TRD_ADDR_2                        0
CUS_TOTAL_NUMBER_OF_ITEMS_5       0
CUS_TOTAL_NUMBER_OF_PACKAGES_6    0
CUS_REF_NO_7                      0
CON_TIN_8                         0
CON_NAME_8                        0
CON_COUNTRY_8                     0
CON_ADDR_8                        0
IMP_TRADING_COUNTRY_11            0
VAL_FINANCIAL_VALUE_12            0
VAL_CURRENCY_12                   0
IMP_CNT_OF_DISPATCH_EXP_CD_15     0
IMP_COUNTRY_OF_ORIGIN_16          0
DEL_DELIVERY_TERM_CODE_20         0
DEL_PLACE_OF_DELIVERY_20          0
TOT_CURRENCY_22                   0
TOT_FINANCIAL_VALUE_22            0
IMP_EXCHANGE_RATE_23              0
IMP_INLAND_TRANSPORT_MODE_25      0
IMP_TRANSPORT_MODE_AT_BODR_26     0
OFF_CODE_30                       0
GDS_GOODS_DESCRIPTION_31          0
GDS_ITEM_NUMBER_32                0
COM_COMBINED_NOMENCLATURE_33      0
IDG_COUNTRY_OF_ORIGIN_34          0
GDS_GROSS_MASS_35           

In [ ]:
# 결측값 제거된 DataFrame을 pickle 파일로 저장
basic_feature_df.to_pickle('./dataset/20_basic_feature_df.pkl')